public enum RepaymentType {
    @JsonProperty("Fixed Principal plus Interest (as it falls due)")
    FIXED_PRINCIPAL_PLUS_INTEREST,

    @JsonProperty("Fixed Repayment (Fixed P & I) followed by Bullet")
    FIXED_REPAYMENT_FOLLOWED_BY_BULLET,

    @JsonProperty("Interest Only followed by Bullet")
    INTEREST_ONLY_FOLLOWED_BY_BULLET,

    @JsonProperty("Interest Roll-up followed by Bullet")
    INTEREST_ROLL_UP_FOLLOWED_BY_BULLET,

    @JsonProperty("Interest Only followed by Fixed Principal followed by Bullet")
    INTEREST_ONLY_FIXED_PRINCIPAL_BULLET,

    @JsonProperty("Interest Only followed by Fixed Repayment (Fixed P & I) followed by Bullet")
    INTEREST_ONLY_FIXED_REPAYMENT_BULLET,

    @JsonProperty("Deferred Repayment followed by Fixed Principal followed by Bullet")
    DEFERRED_REPAYMENT_FIXED_PRINCIPAL_BULLET,

    @JsonProperty("Deferred Repayment followed by Fixed Repayment (Fixed P & I) followed by Bullet")
    DEFERRED_REPAYMENT_FIXED_REPAYMENT_BULLET,

    @JsonProperty("Seasonal")
    SEASONAL,

    @JsonProperty("Sculpted Repayments")
    SCULPTED_REPAYMENTS
}

task-mapping:
  mapping:
    A: "Admin Task"
    B: "Business Analysis"
    C: "Client Support" 

spring:

  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:taskdb  # In-memory H2 database
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      minimum-idle: 1              # Keep 1 idle connection
      maximum-pool-size: 1         # Max 1 connection in pool
      connection-timeout: 30000    # 30 seconds timeout
      idle-timeout: 600000         # 10 minutes idle timeout
      max-lifetime: 1800000        # 30 minutes max lifetime

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
