task-mapping:
  A: "Admin Task"
  B: "Business Analysis"
  C: "Client Support"
  D: "Data Entry"
  E: "Engineering Support"
  F: "Finance Review"
  G: "Governance Check"
  H: "Human Resources"
  I: "IT Support"
  J: "Job Scheduling"
  K: "Knowledge Management"
  L: "Logistics Coordination"
  M: "Marketing Campaign"
  N: "Network Monitoring"
  O: "Operations Task"
  P: "Project Management"
  Q: "Quality Assurance"
  R: "Risk Assessment"
  S: "Software Development"
  T: "Testing and Validation"
  U: "User Experience Review"
  V: "Vendor Management"
  W: "Warehouse Management"
  X: "XML Data Processing"
  Y: "Year-End Review"
  Z: "Zero Downtime Deployment"

spring:
  config:
    import: "configserver:"
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:taskdb  # In-memory H2 database
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      minimum-idle: 1              # Keep 1 idle connection
      maximum-pool-size: 1         # Max 1 connection in pool
      connection-timeout: 30000    # 30 seconds timeout
      idle-timeout: 600000         # 10 minutes idle timeout
      max-lifetime: 1800000        # 30 minutes max lifetime

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
