Authentication and Authorization Flow:

The system initiates an authentication request to API 1 by securely transmitting the Client ID and Client Secret.

Upon successful authentication, API 1 issues an OAuth 2.0 access token.

This access token is then included in the Authorization header (typically as a Bearer token) for subsequent API requests.

Using the obtained token, the system securely invokes API 2, which validates the token and processes the request accordingly.
server:
  port: 8080

spring:
  application:
    name: task-management
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:taskdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 4

logging:
  level:
    root: INFO
