server:
  port: 8080

spring:
  application:
    name: task-management
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:taskdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 4

logging:
  level:
    root: INFO
